#%RAML 1.0 NamedExample
 [ {
                 "productid": 1,
                 "categoryid": 2,
                "name": "Toshiba",
                "description": "Core I 3",
                "video url": "www.toshiba.com",
                "price": 3000  
               },
              {
                 "productid": 1,
                 "categoryid": 2,
                "name": "Toshiba",
                "description": "Core I 3",
                "video url": "www.toshiba.com",
                "price": 3000  
               }
              ]